version: '3.8'

services:
  milvus:
    image: milvusdb/milvus:v2.5.0-beta
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_USE_EMBED: true
      ETCD_DATA_DIR: /var/lib/milvus/etcd
      COMMON_STORAGETYPE: local
    volumes:
      - milvus_data:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 90s

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MILVUS=milvus:19530
      - PG_HOST=postgres
      - PG_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "3001:3001"
    depends_on:
      - milvus
      - postgres
      - redis

  app:
    build:
      context: ../app
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_API=http://api:3001
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  milvus_data:
  postgres_data:
  redis_data:
